### PR TITLE
Hacker Rank SQL Challenge

### PR DESCRIPTION
**Pull request by suriyakrishna**
**Changes:**
1. Added Solutions for Hacker Rank SQL - Basic Join.
2. Added Solutions for Hacker Rank SQL - Alternative Queries.
3. Added Solutions for Hacker Rank SQL - Advanced Join.
4. Added index to Basic Select, Advanced Select, and Aggregation Posts.

### CODE REVIEW

**Comment by yashmehti** [comment]
Hi

**Comment by suriyakrishna** [comment]
Changes looks good and tested locally.

**Comment by suriyakrishna** [comment]
Merging the changes to master

**Comment by suriyakrishna** [comment]
Changes merged to `master` successfully.

**Pull request merged**
